title: "Faveo Documentation"
description: Faveo user, admin, API, integration, plugin and contributing documentation.

# leave trailing slash off
url: https://my-page-organization.github.io

# bump if alterting styles or js
version: 30

defaults:
  - scope:
      type: ""
    values:
      layout: "default"

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

markdown: kramdown

highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
