title: "Faveo Manual Install Documentation"

theme: jekyll-theme-minimal

share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
