title: "Faveo Manual Install Documentation"

<<<<<<< HEAD
theme: jekyll-theme-minimal

share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
=======
theme: jekyll-theme-cayman
>>>>>>> cb95f7747608bd6df203124d91d3b07f6acd7041
